---
driver:
  name: vagrant
  customize:
    memory: 8048
    cpus: 1
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"

provisioner:
  name: chef_solo

platforms:
#  - name: ubuntu-14.04
  - name: centos-7.0
#  - name: ubuntu-15.04

suites:
  - name: default

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[ndb::install]
      - recipe[kagent::install]
      - recipe[apache_hadoop::install]
      - recipe[hadoop_spark::install]
      - recipe[apache_hadoop::nn]
      - recipe[apache_hadoop::dn]
      - recipe[apache_hadoop::rm]
      - recipe[apache_hadoop::nm]
      - recipe[apache_hadoop::jhs]
      - recipe[hadoop_spark::yarn]
      - recipe[hadoop_spark::historyserver]
    attributes:
         apache_hadoop:
            nn:
               private_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
            jhs:
               private_ips: ["10.0.2.15"]
            ps:
               private_ips: ["10.0.2.15"]
         kagent:
            enabled: "false"
         vagrant: "true"
